
name: spiral_animation
description: A Flutter project to display a rotating color-changing spiral with music.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/1.mp3
